kafka:
  bootstrap-servers: localhost:9092
  topics:
    snapshots: "telemetry.snapshots.v1"
    hubs: "telemetry.hubs.v1"
  group-id:
    snapshots: telemetry.analyzer.snapshot
    hubs: telemetry.analyzer.hub

grpc:
  client:
    data-generator:
      address: 'discovery:///data-generator'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/analyzer"
    username: "postgres"
    password: "postgres"
  sql:
    init:
      data-locations: data.sql

logging:
  level:
    ru.yandex.practicum: debug
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace